version: '3.5'
services:
  hubble-api:
    container_name: hubble-api
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - hubble-nginx-server
  hubble-nginx-server:
    container_name: hubble-nginx-server
    build:
      context: ./nginx
    ports:
      - 443:443
      - 80:80
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/server.crt:/etc/ssl/server.crt
      - ./certs/server.key:/etc/ssl/server.key
      - ./certs/ca.crt:/etc/nginx/client_certs/ca.crt
